### ISSUE TITLE
Which JavaScript Linter should we use?

### ISSUE THREAD

**Issue by mgwdev81** [mgwdev81/notice-board#8]
The popular choices seem to be JSHint and ESLint. Are there any others also worth considering?
Laurie, I think you tried JSHint; were you happy with it so far?

**Comment by laurieek** [comment]
I've only used JSHint. It seems like it works well. I'm not familiar with ESLint.

**Comment by mgwdev81** [comment]
We've decided to give ESLint a try as currently it seems to be about as popular as JSHint, and ESLint is the more recent of the two.
